parent=keycloak.v3
import=common/keycloak

styles=css/account.css
stylesCommon=
#stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css
#
#darkMode=false
#
#kcFormGroupClass=form-group
#kcFormGroupLabelClass=form-group-label pf-v5-u-pb-xs
#kcFormLabelClass=form-group-label
#kcFormLabelTextClass=form-group-label-text
#
kcLabelClass=form-label
##kcInputClass=pf-v5-c-form-control
kcInputClass=cl-input
kcInputGroup=input-group
#kcFormHelperTextClass=form-helper-text
#kcInputHelperTextClass=form-helper-text helper-text-inline
#kcInputHelperTextItemClass=form-helper-text-item
#kcInputHelperTextItemTextClass=form-helper-text-item-text
#kcInputGroupItemClass=input-group-item
#kcFill=fill
#kcError=error
#kcLoginFooterBand=login-footer-band
#kcLoginFooterBandItem=login-footer-band-item
#
#kcCheckboxClass=checkbox
#kcCheckboxInputClass=checkbox-input
#kcCheckboxLabelClass=checkbox-label
#kcCheckboxLabelRequiredClass=checkbox-label-required
#
#kcInputRequiredClass=input-required
#kcInputErrorMessageClass=helper-text-error kc-feedback-text
#kcFormControlUtilClass=form-control-utilities
#kcInputErrorIconStatusClass=form-control-icon status
#kcInputErrorIconClass=fas fa-exclamation-circle
#kcAlertClass=alert
#kcAlertIconClass=alert-icon
#kcAlertTitleClass=alert-title
#kcAlertDescriptionClass=alert-description
#kcFormPasswordVisibilityButtonClass=btn btn-control
#kcFormControlToggleIcon=form-control-toggle-icon
#kcFormActionGroupClass=form-actions
#kcFormReadOnlyClass=readonly
#
#kcPanelClass=card
#kcPanelMainClass=card-main
#kcPanelMainBodyClass=card-body
#kcListClass=list
#
kcButtonClass=btn
kcButtonPrimaryClass=btn btn-primary
kcButtonSecondaryClass=btn btn-secondary
#kcButtonBlockClass=btn-block
#kcButtonLinkClass=btn-link
#kcCommonLogoIdP=login-footer-links-item
#kcFormSocialAccountListClass=social-links
#kcFormSocialAccountListItemClass=social-item
#kcFormSocialAccountNameClass=social-provider-name
#kcFormSocialAccountListButtonClass=social-button
#kcFormSocialAccountListButtonDisabledClass=disabled
#kcFormSocialAccountListGridClass=social-grid
#kcFormSocialAccountGridItem=social-grid-item
#
#kcLoginClass=account
#kcFormClass=form
#kcFormCardClass=card
#
#kcResetFlowIcon=fas fa-share-square
#
#kcSelectAuthListClass=select-auth-container
#kcSelectAuthListItemWrapperClass=select-auth-item-wrapper
#kcSelectAuthListItemClass=select-auth-box-parent
#kcSelectAuthListItemHeadingClass=select-auth-box-headline
#kcSelectAuthListItemBodyClass=select-auth-box-body
#kcSelectAuthListItemIconClass=select-auth-box-icon
#kcSelectAuthListItemFillClass=select-auth-item-action
#kcSelectAuthListItemDescriptionClass=select-auth-box-desc
#
#kcRecoveryCodesWarning=alert alert-warning recovery-codes-warning
#kcLogin=login
#kcLoginContainer=login-container
#kcLoginMain=login-main
#kcLoginMainHeader=login-main-header
#kcLoginMainFooter=login-main-footer
#kcLoginMainFooterBand=login-main-footer-band
#kcLoginMainFooterBandItem=login-main-footer-band-item
#kcLoginMainFooterHelperText=login-footer-helper-text
#kcLoginMainTitle=login-main-title
#kcLoginMainHeaderUtilities=login-main-header-utilities
#kcLoginMainBody=login-main-body
#
#kcContentWrapperClass=content-wrapper
#kcWebAuthnDefaultIcon=webauthn-icon
#kcMarginTopClass=margin-top
#
#kcLoginOTPListClass=otp-list
#kcLoginOTPListItemHeaderClass=otp-list-item-header
#kcLoginOTPListItemIconBodyClass=otp-list-item-icon-body
#kcLoginOTPListItemIconClass=fa fa-mobile
#kcLoginOTPListItemTitleClass=otp-list-item-title
#kcLoginOTPListSelectedClass=selected
#
#kcDarkModeClass=dark-mode
#
#kcHtmlClass=account
#kcLogoIdP-facebook=
#kcLogoIdP-google=
#kcLogoIdP-github=
#kcLogoIdP-linkedin=
#kcLogoIdP-instagram=
#kcLogoIdP-microsoft=
#kcLogoIdP-bitbucket=
#kcLogoIdP-gitlab=
#kcLogoIdP-paypal=
#kcLogoIdP-stackoverflow=
#kcLogoIdP-twitter=
#kcLogoIdP-openshift-v4=
