services:
  link-wise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_SUPPORT_EMAIL=${NEXT_PUBLIC_SUPPORT_EMAIL}
        - AUTH_URL=${AUTH_URL}
    container_name: link-wise-app
    ports:
      - "3010:3010"
    environment:
      # Database connection (External MySQL / MariaDB)
      - DATABASE_URL=${DATABASE_URL}

      # NextAuth.js Security
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}

      # OIDC / Keycloak Settings (External Keycloak)
      - AUTH_KEYCLOAK_ID=${AUTH_KEYCLOAK_ID}
      - AUTH_KEYCLOAK_SECRET=${AUTH_KEYCLOAK_SECRET}
      - AUTH_KEYCLOAK_ISSUER=${AUTH_KEYCLOAK_ISSUER}

      # UI Branding & Public URLs
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NEXT_PUBLIC_SUPPORT_EMAIL=${NEXT_PUBLIC_SUPPORT_EMAIL}

      # SMTP Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
    restart: unless-stopped
