[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mariadb]
command=/usr/bin/mysqld_safe
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:keycloak]
command=/opt/keycloak/bin/kc-wrapper.sh --import-realm --optimized --http-port=8080
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
environment=KC_DB="mariadb",KC_DB_URL="jdbc:mariadb://localhost:3306/keycloak",KC_DB_USERNAME="keycloak_user",KC_DB_PASSWORD="keycloak_pass",KC_PROXY="%(ENV_KC_PROXY)s",KC_HOSTNAME="%(ENV_KC_HOSTNAME)s",KC_HOSTNAME_STRICT="%(ENV_KC_HOSTNAME_STRICT)s",KC_HTTP_ENABLED="%(ENV_KC_HTTP_ENABLED)s",KEYCLOAK_ADMIN="admin",KEYCLOAK_ADMIN_PASSWORD="admin"

[program:nextjs]
command=npm start
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
environment=NODE_ENV="production",PORT="3010",NEXT_PUBLIC_APP_URL="%(ENV_NEXT_PUBLIC_APP_URL)s",AUTH_KEYCLOAK_ISSUER="%(ENV_AUTH_KEYCLOAK_ISSUER)s",NEXT_PUBLIC_APP_NAME="%(ENV_NEXT_PUBLIC_APP_NAME)s",NEXT_PUBLIC_SUPPORT_EMAIL="%(ENV_NEXT_PUBLIC_SUPPORT_EMAIL)s",AUTH_URL="%(ENV_AUTH_URL)s",SMTP_HOST="%(ENV_SMTP_HOST)s",SMTP_PORT="%(ENV_SMTP_PORT)s",SMTP_USER="%(ENV_SMTP_USER)s",SMTP_PASS="%(ENV_SMTP_PASS)s",SMTP_FROM_NAME="%(ENV_SMTP_FROM_NAME)s",SMTP_FROM_EMAIL="%(ENV_SMTP_FROM_EMAIL)s"
